name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Apt dependencies
        shell: bash
        run: |
          sudo apt -y update
          sudo apt install -y libgcc-9-dev \
                              libstdc++-9-dev \
                              libembree-dev \
                              python3-dev \
                              libhdf5-dev \
                              libeigen3-dev \
                              cmake

      - name: Python dependencies
        shell: bash
        run: |
          pip3 install numpy \
                      cython==0.29.37 \
                      scipy \
                      matplotlib \
                      h5py \
                      pytest \
                      pytest-cov \
                      codecov

      - name: Clone MOAB
        shell: bash
        run: |
          cd ~
          git clone https://bitbucket.org/fathomteam/moab.git
          cd moab
          git checkout 5.5.1

      - name: MOAB SHA Environment Variable
        shell: bash
        run: |
          echo "MOAB_SHA=$(cd ~/moab && git rev-parse HEAD)" >> $GITHUB_ENV

      - name: MOAB Cache
        id: moab-cache
        uses: actions/cache@v3
        env:
          cache-name: cache-moab
        with:
          path: |
            ~/moab
            ~/opt
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ env.MOAB_SHA }}

      - if: ${{ steps.moab-cache.outputs.cache-hit != 'true' }}
        name: Build MOAB
        shell: bash
        run: |
          cd ~/moab
          mkdir build
          cd build
          cmake -DENABLE_HDF5=ON -DENABLE_BLASLAPACK=OFF -DENABLE_PYMOAB=ON -DCMAKE_INSTALL_PREFIX=$HOME/opt -DCMAKE_BUILD_TYPE=Release ..
          make -j4

      - name: Install PyMOAB
        shell: bash
        run: |
          cd ~/moab/build
          pip3 install .

      - name: Install PyDAGMC
        shell: bash
        run: |
          pip install .

      - name: Test
        shell: bash
        run: |
          pytest -v .

      - name: tmate debug
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3